#!/usr/bin/with-contenv bash
# shellcheck shell=bash

main() {
    if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
        mariadb-install-db --datadir="${DATADIR}" --auth-root-authentication-method=normal --user=abc

        # own the folder the pid for mysql runs in
        lsiown -R abc:abc /run/mysqld
        lsiown -R abc:abc /config

        return
    fi

    mariadb-install-db --datadir="${DATADIR}" --auth-root-authentication-method=normal
}

main