secrets:
  mariadb_root_password:
    file: ./secrets/mariadb_root_password.txt
  mariadb_user_example_password: # Password for user 'example'
    file: ./secrets/mariadb_user_example_password.txt

networks:
  default:
  database:

services:
  database:
    image: ghcr.io/n0rthernl1ghts/mariadb:latest
    deploy:
      restart_policy:
        condition: any
      resources:
        reservations:
          memory: 2G
        limits:
          memory: 3G
    environment:
      PUID: 1000
      PGID: 1000
      MARIADB_INIT_USERS: 'example,app,docs-app' # Notice that the password for 'example' is set in the secrets section
      MARIADB_INIT_DATABASES: 'app,cars,docs'
      FORCE_CONFIG_OVERWRITE: 'false'
    volumes:
      - ./data/mariadb/config:/config
      - ./data/mariadb/data:/var/lib/mysql
      - ./data/mariadb/log:/var/log/mysql
    secrets:
      - mariadb_root_password
      - mariadb_user_example_password
    networks:
      default: {aliases: [database]}
      database: null
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 20s
      retries: 3