#!/command/with-contenv bash
# shellcheck shell=bash

# This is safeguard if init-mariadb-provision is somehow not stopped
# init-mariadb-provision-completed main
main() {
    # This will prepend service name to all output from here
    exec > >(while read -r line; do echo "[init-mariadb-provision-completed] ${line}"; done) 2>&1

    if db-util healthcheck >/dev/null 2>&1; then
        echo "Service is still running. Shutting down..."

        # Suppress output
        if ! mariadb-admin --user=root shutdown >/dev/null 2>&1; then
            echo "Fatal error: Failed to shutdown instance"
            return 1
        fi
    fi
}
main
