#!/usr/bin/with-contenv bash

if [ -f ./setup ]
then
  source ./setup
fi

if [ -d ./custom.d ]
then
  for FILE in $(find ./custom.d -type f -iname \*.sh | sort)
  do
    source ${FILE}
  done
fi

STARTCMD="mysqld_safe"

echo "> starting mariadb service"
exec ${STARTCMD}
