#!/usr/bin/with-contenv bash

INIT_FILE='/tmp/mariadb-boot.sql'

echo "> Starting mariadb service"

# Init file will exist only if database was not previously initialized (@see /etc/cont-init.d/02-init-database)
if [ -f "${INIT_FILE}" ]; then
  echo "> With database init"
  exec mysqld_safe --init-file="${INIT_FILE}"
fi

exec mysqld_safe