#!/usr/bin/with-contenv bash
set -e
echo "Attempting to safely shutdown mariadb service..."
mysql << EOF
   STOP SLAVE;
   SET GLOBAL innodb_fast_shutdown=0;
   SET GLOBAL innodb_max_dirty_pages_pct=0;
   FLUSH LOCAL TABLES;
   FLUSH TABLES WITH READ LOCK;
EOF

mysqladmin shutdown -v
