#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -o pipefail

# Main function
main() {
    exec > >(while read line; do echo "[init-mariadb-bootstrap] ${line}"; done) 2>&1

    /app/mariadb-bootstrap
}

main "$@"
