#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -o pipefail

start_mariadb() {
    mariadbd --datadir="${DATADIR}" --user=abc
}

stop_mariadb() {
    mariadb-admin --user=root shutdown
}

# Main function
main() {
    exec > >(while read -r line; do echo "[init-mariadb-bootstrap] ${line}"; done) 2>&1

    local bootstrapPid

    printf "Starting temporary MariaDB instance for bootstrap...\n"
    start_mariadb &

    /app/mariadb-bootstrap &
    bootstrapPid=$!

    wait "${bootstrapPid}"
    kill -TERM "${bootstrapPid}" 2>/dev/null

    printf "Stopping MariaDB instance\n"
    stop_mariadb

    printf "Bootstrap completed\n"
}

main "$@"
