#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -eo pipefail

create-env-file() {
    local env_var="${1:?Environment variable is required}"
    local env_value="${2:?Environment value is required}"

    if [ -f "/var/run/s6/container_environment/${env_var}" ]; then
        echo "Updating env file '${env_var}'"
    else
        echo "Creating env file '${env_var}'"
    fi

    # Inject env into s6 environment
    echo -n "${env_value}" > "/var/run/s6/container_environment/${env_var}"
}

# init-mariadb-initdb-adapter main
main() {
    # Find legacy variables and create env overrides/mappings

    if [ -n "${MARIADB_USERNAME}" ]; then
        echo "Warning: Deprecated variable 'MARIADB_USERNAME' is ignored during initdb"
        echo "Please use 'MARIADB_INIT_USERS' instead"
    fi

    if [ -n "${MARIADB_PASSWORD}" ]; then
        echo "Warning: Deprecated variable 'MARIADB_PASSWORD' is ignored during initdb"
        echo "Please use 'MARIADB_INIT_USERS' instead"
    fi

    if [ -n "${MARIADB_DATABASE}" ]; then
        echo "Warning: Deprecated variable 'MARIADB_DATABASE'"
        echo "Please use 'MARIADB_INIT_DATABASES' instead"
    fi

    if [ -n "${MARIADB_ROOT_PASSWORD}" ]; then
        create-env-file "MYSQL_ROOT_PASSWORD" "${MARIADB_ROOT_PASSWORD}"
    fi
    
}
main
