#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -eo pipefail

create-env-file() {
    local envVar="${1:?Environment variable is required}"
    local envValue="${2:?Environment value is required}"

    if [ -f "/var/run/s6/container_environment/${envVar}" ]; then
        echo "Updating env file '${envVar}'"
    else
        echo "Creating env file '${envVar}'"
    fi

    # Inject env into s6 environment
    echo -n "${envValue}" > "/var/run/s6/container_environment/${envVar}"
}

# init-mariadb-initdb-adapter main
main() {
    # Find legacy variables and create env overrides/mappings to MYSQL_PASSWORD/MYSQL_DATABASE/MYSQL_USER

    if [ -n "${MARIADB_USERNAME}" ]; then
        create-env-file "MYSQL_USER" "${MARIADB_USERNAME}"
    fi

    if [ -n "${MARIADB_PASSWORD}" ]; then
        create-env-file "MYSQL_PASSWORD" "${MARIADB_PASSWORD}"
    fi

    if [ -n "${MARIADB_DATABASE}" ]; then
        create-env-file "MYSQL_DATABASE" "${MARIADB_DATABASE}"
    fi

    if [ -n "${MARIADB_ROOT_PASSWORD}" ]; then
        create-env-file "MYSQL_ROOT_PASSWORD" "${MARIADB_ROOT_PASSWORD}"
    fi
    
}
main
