#!/usr/bin/env bash
# shellcheck shell=bash

set -o pipefail

start_mariadb() {
    mariadbd --datadir="${DATADIR}" --user=abc &
}

# Generate a random password
generate_password() {
    openssl rand -base64 32 | tr -d "=+/" | cut -c1-16
}

# Create a user function
create_user() {
    local user="${1:?User required}"
    local password="${2:-}"
    local is_random_password=0

    echo "> Creating user '${user}'"

    if db-util user-exists "${user}"; then
        echo "> User '${user}' already exists"
        return 1
    fi

    if [ -z "${password}" ]; then
        password=$(generate_password)
        is_random_password=1
    fi

    if db-util user-create "${user}" "${password}"; then
        echo "> User '${user}' created with password '${password}'"

        if [ "${is_random_password}" -eq 1 ]; then
            echo "${password}" >"/config/.${user}.password"
            echo "  Random password generated"
            echo "  Password saved in /config/.${user}.password"
            echo "  It is recommended to remove this file after retrieving the password"
        fi

        return 0
    fi

    echo "> Error: Failed to create user '${user}'"
    return 1
}

# Create a database function
create_database() {
    local database="${1:?Database required}"

    echo "> Creating database '${database}'"

    if db-util db-exists "${database}"; then
        echo "> Database '${database}' already exists"
        return 0
    fi

    if db-util db-create "${database}"; then
        echo "> Database '${database}' created"
        return 0
    fi

    echo "> Error: Failed to create database '${database}'"
    return 1
}

# Function to create batch users
create_batch_users() {
    local users

    users=$(echo "${1:?Users required}" | tr "|" "\n")

    for user in ${users}; do
        IFS=':' read -r username password <<<"${user}"
        create_user "${username}" "${password:-}"
        sleep 0.1
    done
}

# Function to create batch databases
create_batch_databases() {
    local databases

    databases=$(echo "${1:?Databases required}" | tr "," "\n")

    for database in ${databases}; do
        IFS=':' read -r database_name assigned_user <<<"${database}"

        if create_database "${database_name}"; then
            if [ -n "${assigned_user}" ]; then
                echo "> Assigning user '${assigned_user}' to database '${database_name}'"
                db-util db-grant-privileges "${assigned_user}" "${database_name}"
            elif [ -n "${MARIADB_USERNAME}" ]; then
                echo "> Assigning user '${MARIADB_USERNAME}' to database '${database_name}'"
                db-util db-grant-privileges "${MARIADB_USERNAME}" "${database_name}"
            fi
        fi
        sleep 0.1
    done
}

function checkHashUpdate() {
    local inputString="${1:?Input string required}"
    local hashFile="${2:?Hash file required}"
    local calculatedHash

    # Calculate SHA256 hash of the input string
    calculatedHash=$(echo -n "${inputString}" | sha256sum | awk '{print $1}')

    if [ ! -f "${hashFile}" ]; then
        printf "> Warning: Hash file '%s' doesn't exist. Creating a new one with hash '%s'.\n" "${hashFile}" "${calculatedHash}" >&2

        # Create a new hash file with the new hash and return 1 to indicate that the hash has changed (since there was no previous hash)
        printf "%s" "${calculatedHash}" >"${hashFile}"
        return 1
    fi

    # Compare the new hash with the stored hash
    if [ "${calculatedHash}" == "$(cat "${hashFile}")" ]; then
        # Hashes are the same, meaning there is nothing to update
        return 0
    fi

    # Update the hash file with the new hash and return 1 to indicate that the hash has changed
    printf "%s" "${calculatedHash}" >"${hashFile}"
    return 1
}

# Main function
main() {
    echo "> [MariaDB Runtime Bootstrap v2.1]"

    start_mariadb

    until db-util healthcheck >/dev/null 2>&1; do
        echo "> Waiting for MariaDB to become ready..."
        sleep 1
    done

    echo "> MariaDB ready. Proceeding with initialization"

    if [ -n "${MARIADB_USERNAME}" ]; then
        echo "> Warning: MARIADB_USERNAME is deprecated. Please use MARIADB_INIT_USERS instead"

        local username_entry="${MARIADB_USERNAME}:${MARIADB_PASSWORD}"
        if [ -n "${MARIADB_INIT_USERS}" ]; then
            MARIADB_INIT_USERS="${MARIADB_INIT_USERS}|${username_entry}"
        else
            MARIADB_INIT_USERS="${username_entry}"
        fi
    fi

    if [ -n "${MARIADB_DATABASE}" ]; then
        echo "> Warning: MARIADB_DATABASE is deprecated. Please use MARIADB_INIT_DATABASES instead"

        if [ -n "${MARIADB_INIT_DATABASES}" ]; then
            MARIADB_INIT_DATABASES="${MARIADB_INIT_DATABASES},${MARIADB_DATABASE}"
        else
            MARIADB_INIT_DATABASES="${MARIADB_DATABASE}"
        fi
    fi

    sleep 1

    echo "> Calculating MARIADB_INIT_USERS and MARIADB_INIT_DATABASES hashes..."

    if checkHashUpdate "${MARIADB_INIT_USERS}" "/config/.mariadb_init_users.hash"; then
        printf "> MARIADB_INIT_USERS unchanged. Skipping users initialization.\n"
        MARIADB_INIT_USERS=""
    fi

    if checkHashUpdate "${MARIADB_INIT_DATABASES}" "/config/.mariadb_init_databases.hash"; then
        printf "> MARIADB_INIT_DATABASES unchanged. Skipping databases initialization.\n"
        MARIADB_INIT_DATABASES=""
    fi

    if [ -n "${MARIADB_INIT_USERS}" ]; then
        echo "> Initializing users..."
        create_batch_users "${MARIADB_INIT_USERS}"
        db-util flush-privileges
    fi

    if [ -n "${MARIADB_INIT_DATABASES}" ]; then
        echo "> Initializing databases..."
        create_batch_databases "${MARIADB_INIT_DATABASES}"
    fi

    mariadb-admin -u root --password="${MARIADB_ROOT_PASSWORD}" shutdown

    echo "> Bootstrap complete."
}

main "$@"
