#!/usr/bin/env sh

if [ ! -d "/var/lib/mysql/mysql" ]; then
  mkdir -p /var/lib/mysql
  attr /var/lib/mysql/ true mysql:mysql 0770 2771
fi

if [ ! -d "/var/log/mysql" ]; then
  mkdir -p /var/log/mysql
  attr /var/log/mysql/ true mysql:mysql 0770 2771
fi