#!/usr/bin/with-contenv bash
set -e

INIT_FILE="/tmp/mariadb-boot.sql"

# Delete init file if already exists
rm -f "${INIT_FILE}"

if [ ! -d "/var/lib/mysql/mysql" ]
then
  if [ -z "${MARIADB_ROOT_PASSWORD}" ]
  then
    echo >&2 "Error: Database is uninitialized and MARIADB_ROOT_PASSWORD not set"
    s6-svscanctl -t /var/run/s6/services
    exit 1
  fi

  echo "> running mysql_install_db..."
  mysql_install_db --user=mysql --datadir="/var/lib/mysql"
  echo "> finished mysql_install_db"

  echo "" >| ${INIT_FILE}
  echo "DELETE FROM mysql.user;" >> ${INIT_FILE}
  echo "CREATE USER 'root'@'localhost';" >> ${INIT_FILE}
  echo "CREATE USER 'root'@'%' IDENTIFIED BY '${MARIADB_ROOT_PASSWORD}';" >> ${INIT_FILE}
  echo "GRANT ALL ON *.* TO 'root'@'localhost' WITH GRANT OPTION;" >> ${INIT_FILE}
  echo "GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION;" >> ${INIT_FILE}
  echo "DROP DATABASE IF EXISTS test;" >> ${INIT_FILE}
  echo "FLUSH PRIVILEGES;" >> ${INIT_FILE}

  if [[ -n "${MARIADB_USERNAME}" && -n "${MARIADB_DATABASE}" ]]
  then
    DATABASES=$(echo ${MARIADB_DATABASE} | tr "," "\n")

    for DATABASE in ${DATABASES}
    do
      echo "CREATE DATABASE IF NOT EXISTS \`${DATABASE}\`;" >> ${INIT_FILE}
      echo "GRANT ALL PRIVILEGES ON \`${DATABASE}\`.* TO '${MARIADB_USERNAME}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';" >> ${INIT_FILE}
    done

    echo "FLUSH PRIVILEGES;" >> ${INIT_FILE}
  fi

  if [[ -n "${MARIADB_USERNAME}" && -z "${MARIADB_DATABASE}" ]]
  then
    echo "CREATE DATABASE IF NOT EXISTS \`${MARIADB_USERNAME}\`;" >> ${INIT_FILE}
    echo "GRANT ALL PRIVILEGES ON \`${MARIADB_USERNAME}\`.* TO '${MARIADB_USERNAME}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';" >> ${INIT_FILE}
    echo "FLUSH PRIVILEGES;" >> ${INIT_FILE}
  fi
fi